export const PARTIAL_PAYMENT_PENDING = "PARTIAL_PAYMENT_PENDING";
export const PARTIAL_PAYMENT_SUCCESS = "PARTIAL_PAYMENT_SUCCESS";
export const PARTIAL_PAYMENT_ERROR = "PARTIAL_PAYMENT_ERROR";
export const CLEAR_PARTIAL_PAYMENT_MESSAGES = "CLEAR_PARTIAL_PAYMENT_MESSAGES";
