export const DELETE_MODERATOR_PENDING = "DELETE_MODERATOR_PENDING";
export const DELETE_MODERATOR_SUCCESS = "DELETE_MODERATOR_SUCCESS";
export const DELETE_MODERATOR_ERROR = "DELETE_MODERATOR_ERROR";
