export const ADD_SALE_PENDING = "ADD_SALE_PENDING";
export const ADD_SALE_SUCCESS = "ADD_SALE_SUCCESS";
export const ADD_SALE_ERROR = "ADD_SALE_ERROR";
export const CLEAR_SALE_MESSAGE = "CLEAR_SALE_MESSAGE";

export const GET_SALE_PENDING = "GET_SALE_PENDING";
export const GET_SALE_SUCCESS = "GET_SALE_SUCCESS";
export const GET_SALE_ERROR = "GET_SALE_ERROR";
