export const BRANCH_PENDING = "BRANCH_PENDING";
export const BRANCH_SUCCESS = "BRANCH_SUCCESS";
export const BRANCH_ERROR = "BRANCH_ERROR";

export const BRANCH_ADD_PENDING = "BRANCH_ADD_PENDING";
export const BRANCH_ADD_SUCCESS = "BRANCH_ADD_SUCCESS";
export const BRANCH_ADD_ERROR = "BRANCH_ADD_ERROR";

export const ADD_PRODUCT_TO_BRANCH_PENDING = "ADD_PRODUCT_TO_BRANCH_PENDING";
export const ADD_PRODUCT_TO_BRANCH_SUCCESS = "ADD_PRODUCT_TO_BRANCH_SUCCESS";
export const ADD_PRODUCT_TO_BRANCH_ERROR = "ADD_PRODUCT_TO_BRANCH_ERROR";

export const CLEAR_BRANCH_MESSAGES = "CLEAR_BRANCH_MESSAGES";
