// Customers action types
export const CUSTOMERS_LOADING = "CUSTOMERS_LOADING";
export const CUSTOMERS_SUCCESS = "CUSTOMERS_SUCCESS";
export const CUSTOMERS_ERROR = "CUSTOMERS_ERROR";

export const ADD_CUSTOMER_SUCCESS = "ADD_CUSTOMER_SUCCESS";
export const UPDATE_CUSTOMER_SUCCESS = "UPDATE_CUSTOMER_SUCCESS";
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS";

// Customer purchase history action types
export const CUSTOMER_PURCHASE_HISTORY_LOADING = "CUSTOMER_PURCHASE_HISTORY_LOADING";
export const CUSTOMER_PURCHASE_HISTORY_SUCCESS = "CUSTOMER_PURCHASE_HISTORY_SUCCESS";
export const CUSTOMER_PURCHASE_HISTORY_ERROR = "CUSTOMER_PURCHASE_HISTORY_ERROR";

// Customer loyalty points action types
export const CUSTOMER_LOYALTY_POINTS_LOADING = "CUSTOMER_LOYALTY_POINTS_LOADING";
export const CUSTOMER_LOYALTY_POINTS_SUCCESS = "CUSTOMER_LOYALTY_POINTS_SUCCESS";
export const CUSTOMER_LOYALTY_POINTS_ERROR = "CUSTOMER_LOYALTY_POINTS_ERROR";