export const EXPENSES_PENDING = "EXPENSES_PENDING";
export const EXPENSES_SUCCESS = "EXPENSES_SUCCESS";
export const EXPENSES_ERROR = "EXPENSES_ERROR";
export const CLEAR_EXPENSES_MESSAGES = "CLEAR_EXPENSES_MESSAGES";

export const ADD_EXPENSE_PENDING = "ADD_EXPENSE_PENDING";
export const ADD_EXPENSE_SUCCESS = "ADD_EXPENSE_SUCCESS";
export const ADD_EXPENSE_ERROR = "ADD_EXPENSE_ERROR";
