// Inventory Actions
export const FETCH_INVENTORY_ITEMS = "FETCH_INVENTORY_ITEMS";
export const FETCH_INVENTORY_ITEMS_SUCCESS = "FETCH_INVENTORY_ITEMS_SUCCESS";
export const FETCH_INVENTORY_ITEMS_ERROR = "FETCH_INVENTORY_ITEMS_ERROR";

export const ADD_INVENTORY_ITEM = "ADD_INVENTORY_ITEM";
export const ADD_INVENTORY_ITEM_SUCCESS = "ADD_INVENTORY_ITEM_SUCCESS";
export const ADD_INVENTORY_ITEM_ERROR = "ADD_INVENTORY_ITEM_ERROR";

export const UPDATE_INVENTORY_ITEM = "UPDATE_INVENTORY_ITEM";
export const UPDATE_INVENTORY_ITEM_SUCCESS = "UPDATE_INVENTORY_ITEM_SUCCESS";
export const UPDATE_INVENTORY_ITEM_ERROR = "UPDATE_INVENTORY_ITEM_ERROR";

export const DELETE_INVENTORY_ITEM = "DELETE_INVENTORY_ITEM";
export const DELETE_INVENTORY_ITEM_SUCCESS = "DELETE_INVENTORY_ITEM_SUCCESS";
export const DELETE_INVENTORY_ITEM_ERROR = "DELETE_INVENTORY_ITEM_ERROR";

export const FETCH_SUPPLIERS = "FETCH_SUPPLIERS";
export const FETCH_SUPPLIERS_SUCCESS = "FETCH_SUPPLIERS_SUCCESS";
export const FETCH_SUPPLIERS_ERROR = "FETCH_SUPPLIERS_ERROR";

export const ADD_SUPPLIER = "ADD_SUPPLIER";
export const ADD_SUPPLIER_SUCCESS = "ADD_SUPPLIER_SUCCESS";
export const ADD_SUPPLIER_ERROR = "ADD_SUPPLIER_ERROR";

export const UPDATE_SUPPLIER = "UPDATE_SUPPLIER";
export const UPDATE_SUPPLIER_SUCCESS = "UPDATE_SUPPLIER_SUCCESS";
export const UPDATE_SUPPLIER_ERROR = "UPDATE_SUPPLIER_ERROR";

export const DELETE_SUPPLIER = "DELETE_SUPPLIER";
export const DELETE_SUPPLIER_SUCCESS = "DELETE_SUPPLIER_SUCCESS";
export const DELETE_SUPPLIER_ERROR = "DELETE_SUPPLIER_ERROR";

export const FETCH_INVENTORY_ALERTS = "FETCH_INVENTORY_ALERTS";
export const FETCH_INVENTORY_ALERTS_SUCCESS = "FETCH_INVENTORY_ALERTS_SUCCESS";
export const FETCH_INVENTORY_ALERTS_ERROR = "FETCH_INVENTORY_ALERTS_ERROR";

export const MARK_ALERT_AS_READ = "MARK_ALERT_AS_READ";
export const MARK_ALERT_AS_READ_SUCCESS = "MARK_ALERT_AS_READ_SUCCESS";
export const MARK_ALERT_AS_READ_ERROR = "MARK_ALERT_AS_READ_ERROR";

export const FETCH_REORDER_REQUESTS = "FETCH_REORDER_REQUESTS";
export const FETCH_REORDER_REQUESTS_SUCCESS = "FETCH_REORDER_REQUESTS_SUCCESS";
export const FETCH_REORDER_REQUESTS_ERROR = "FETCH_REORDER_REQUESTS_ERROR";

export const CREATE_REORDER_REQUEST = "CREATE_REORDER_REQUEST";
export const CREATE_REORDER_REQUEST_SUCCESS = "CREATE_REORDER_REQUEST_SUCCESS";
export const CREATE_REORDER_REQUEST_ERROR = "CREATE_REORDER_REQUEST_ERROR";

export const UPDATE_REORDER_REQUEST = "UPDATE_REORDER_REQUEST";
export const UPDATE_REORDER_REQUEST_SUCCESS = "UPDATE_REORDER_REQUEST_SUCCESS";
export const UPDATE_REORDER_REQUEST_ERROR = "UPDATE_REORDER_REQUEST_ERROR";

export const FETCH_WAREHOUSE_LOCATIONS = "FETCH_WAREHOUSE_LOCATIONS";
export const FETCH_WAREHOUSE_LOCATIONS_SUCCESS = "FETCH_WAREHOUSE_LOCATIONS_SUCCESS";
export const FETCH_WAREHOUSE_LOCATIONS_ERROR = "FETCH_WAREHOUSE_LOCATIONS_ERROR";

export const ADD_WAREHOUSE_LOCATION = "ADD_WAREHOUSE_LOCATION";
export const ADD_WAREHOUSE_LOCATION_SUCCESS = "ADD_WAREHOUSE_LOCATION_SUCCESS";
export const ADD_WAREHOUSE_LOCATION_ERROR = "ADD_WAREHOUSE_LOCATION_ERROR";

export const UPDATE_WAREHOUSE_LOCATION = "UPDATE_WAREHOUSE_LOCATION";
export const UPDATE_WAREHOUSE_LOCATION_SUCCESS = "UPDATE_WAREHOUSE_LOCATION_SUCCESS";
export const UPDATE_WAREHOUSE_LOCATION_ERROR = "UPDATE_WAREHOUSE_LOCATION_ERROR";

export const DELETE_WAREHOUSE_LOCATION = "DELETE_WAREHOUSE_LOCATION";
export const DELETE_WAREHOUSE_LOCATION_SUCCESS = "DELETE_WAREHOUSE_LOCATION_SUCCESS";
export const DELETE_WAREHOUSE_LOCATION_ERROR = "DELETE_WAREHOUSE_LOCATION_ERROR";

// Return Entry Actions
export const FETCH_RETURN_ENTRIES = "FETCH_RETURN_ENTRIES";
export const FETCH_RETURN_ENTRIES_SUCCESS = "FETCH_RETURN_ENTRIES_SUCCESS";
export const FETCH_RETURN_ENTRIES_ERROR = "FETCH_RETURN_ENTRIES_ERROR";

export const ADD_RETURN_ENTRY = "ADD_RETURN_ENTRY";
export const ADD_RETURN_ENTRY_SUCCESS = "ADD_RETURN_ENTRY_SUCCESS";
export const ADD_RETURN_ENTRY_ERROR = "ADD_RETURN_ENTRY_ERROR";

export const UPDATE_RETURN_ENTRY = "UPDATE_RETURN_ENTRY";
export const UPDATE_RETURN_ENTRY_SUCCESS = "UPDATE_RETURN_ENTRY_SUCCESS";
export const UPDATE_RETURN_ENTRY_ERROR = "UPDATE_RETURN_ENTRY_ERROR";

export const DELETE_RETURN_ENTRY = "DELETE_RETURN_ENTRY";
export const DELETE_RETURN_ENTRY_SUCCESS = "DELETE_RETURN_ENTRY_SUCCESS";
export const DELETE_RETURN_ENTRY_ERROR = "DELETE_RETURN_ENTRY_ERROR";

// Damage Entry Actions
export const FETCH_DAMAGE_ENTRIES = "FETCH_DAMAGE_ENTRIES";
export const FETCH_DAMAGE_ENTRIES_SUCCESS = "FETCH_DAMAGE_ENTRIES_SUCCESS";
export const FETCH_DAMAGE_ENTRIES_ERROR = "FETCH_DAMAGE_ENTRIES_ERROR";

export const ADD_DAMAGE_ENTRY = "ADD_DAMAGE_ENTRY";
export const ADD_DAMAGE_ENTRY_SUCCESS = "ADD_DAMAGE_ENTRY_SUCCESS";
export const ADD_DAMAGE_ENTRY_ERROR = "ADD_DAMAGE_ENTRY_ERROR";

export const UPDATE_DAMAGE_ENTRY = "UPDATE_DAMAGE_ENTRY";
export const UPDATE_DAMAGE_ENTRY_SUCCESS = "UPDATE_DAMAGE_ENTRY_SUCCESS";
export const UPDATE_DAMAGE_ENTRY_ERROR = "UPDATE_DAMAGE_ENTRY_ERROR";

export const DELETE_DAMAGE_ENTRY = "DELETE_DAMAGE_ENTRY";
export const DELETE_DAMAGE_ENTRY_SUCCESS = "DELETE_DAMAGE_ENTRY_SUCCESS";
export const DELETE_DAMAGE_ENTRY_ERROR = "DELETE_DAMAGE_ENTRY_ERROR";

export const CLEAR_INVENTORY_MESSAGE = "CLEAR_INVENTORY_MESSAGE";