// Get Valuation

export const GET_BRANCH_VALUATION_PENDING = "GET_BRANCH_VALUATION_PENDING";
export const GET_BRANCH_VALUATION_SUCCESS = "GET_BRANCH_VALUATION_SUCCESS";
export const GET_BRANCH_VALUATION_ERROR = "GET_BRANCH_VALUATION_ERROR";

// Delete Valuation
export const DELETE_BRANCH_VALUATION_PENDING =
  "DELETE_BRANCH_VALUATION_PENDING";
export const DELETE_BRANCH_VALUATION_SUCCESS =
  "DELETE_BRANCH_VALUATION_SUCCESS";
export const DELETE_BRANCH_VALUATION_ERROR = "DELETE_BRANCH_VALUATION_ERROR";

// clear error
export const CLEAR_BRANCH_VALUATION_MESSAGE = "CLEAR_BRANCH_VALUATION_MESSAGE";
